gamepredictor/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.user_login),
    url(r'^login/', views.user_login, name='user_login'),
    url(r'^logout/', views.user_logout, name='user_logout'),
    url(r'^signup/', views.user_signup, name='user_signup'),
]

gamepredictor/gamepredictor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from games import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^games/', include('games.urls')),
    url(r'^stats/', include('stats.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gamepredictor/games/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^submit_data/', views.submit_data, name='data'),
]

gamepredictor/stats/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.stats, name='stats'),
]

gamepredictor/accounts/models.py
from django.db import models

# Create your models here.

gamepredictor/games/models.py
from django.db import models
from django.contrib.auth.admin import User


class GamesList(models.Model):
    id = models.AutoField(primary_key=True)
    game_date = models.DateField(blank=True, null=True)
    away_team = models.CharField(max_length=32, blank=True, null=True)
    away_team_score = models.IntegerField(blank=True, null=True)
    home_team = models.CharField(max_length=32, blank=True, null=True)
    home_team_score = models.IntegerField(blank=True, null=True)
    game_id = models.CharField(max_length=12, blank=True, null=True)
    overtime = models.CharField(max_length=2, blank=True, null=True)
    attendance = models.IntegerField(blank=True, null=True)

    def winner(self):
        if self.away_team_score:
            if self.away_team_score > self.home_team_score:
                return self.away_team
            else:
                return self.home_team
        return "Game has not yet been played"

    def is_overtime(self):
        if self.overtime != '':
            return True
        return False


class GamePredictions(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User)
    game_date = models.DateField(null=False)
    game_id = models.CharField(max_length=12, blank=False, null=False)
    prediction = models.CharField(max_length=32, blank=False, null=False)


class TeamStats(models.Model):
    id = models.AutoField(primary_key=True)
    team = models.CharField(max_length=32, blank=False, null=False)
    year = models.CharField(max_length=7, blank=False, null=False)
    wins = models.IntegerField()
    losses = models.IntegerField()
    otl = models.IntegerField()
    streak = models.CharField(max_length=3)
    logo = models.ImageField(upload_to="static/logos")


class UserStats(models.Model):
    id = models.OneToOneField(User, primary_key=True)
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    otl = models.IntegerField(default=0)

gamepredictor/stats/models.py
from django.db import models

# Create your models here.

gamepredictor/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


def user_login(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request, 'account/login.html',
                          {'error': 'The username and password combination does not exist'})
    else:
        return render(request, 'accounts/login.html')


def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


def user_signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                User.objects.get(username=request.POST['username'])
                print("Inside try")
                return render(request, 'accounts/signup.html', {'error': 'Username has already been taken'})
            except:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                print("Inside except")
                login(request, user)
                return redirect('home')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords do not match'})
    else:
        return render(request, 'accounts/signup.html')

gamepredictor/games/views.py
import datetime, json
from django.shortcuts import render, redirect
from .grab_scores import get_games_from_db
from .models import GamePredictions, TeamStats


def home(request):
    today = datetime.datetime.strftime(datetime.datetime.today(), '%Y-%m-%d')
    games = get_games_from_db(today)
    games_data = []
    team_stats_raw = TeamStats.objects.all()
    team_stats = {}

    # refactor these into other modules
    for team in team_stats_raw:
        team_stats[team.team] = {
            'wins': team.wins,
            'losses': team.losses,
            'otl': team.otl,
            'streak': team.streak,
            'logo': team.logo,
        }

    for game in games:
        away_team = game.away_team
        home_team = game.home_team
        games_data.append({
            'game_date': game.game_date,
            'away_team': game.away_team,
            'away_team_score': game.away_team_score,
            'home_team': game.home_team,
            'home_team_score': game.home_team_score,
            'overtime': game.overtime,
            'attendance': game.attendance,
            'game_id': game.game_id,
            'away_team_wins': team_stats[away_team]['wins'],
            'away_team_losses': team_stats[away_team]['losses'],
            'away_team_otl': team_stats[away_team]['otl'],
            'away_team_logo': team_stats[away_team]['logo'],
            'home_team_wins': team_stats[home_team]['wins'],
            'home_team_losses': team_stats[home_team]['losses'],
            'home_team_otl': team_stats[home_team]['otl'],
            'home_team_logo': team_stats[home_team]['logo'],
        })

    return render(request, 'games/home.html', {'games_data': games_data, 'today': today})


def submit_data(request):
    if request.method == 'POST':
        submitted_data = json.loads(request.body.decode("utf-8"))
        for game in submitted_data:
            GamePredictions.objects.get_or_create(game_id=game,
                                                  prediction=submitted_data[game],
                                                  user_id_id=request.user.id,
                                                  game_date=datetime.datetime.strftime(datetime.datetime.today(),
                                                                                       '%Y-%m-%d'))
        return redirect('home')

gamepredictor/stats/views.py
from django.shortcuts import render
from games.models import UserStats


def stats(request):
    user_record = UserStats.objects.get(id=request.user.id)
    return render(request, 'stats/stats.html', {'user_record': user_record})

gamepredictor/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>

{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}


<form method="POST" action="{% url 'accounts:user_login' %}">
    {% csrf_token %}

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    {% endif %}

    <input type="text" name="username" placeholder="Username" />
    <br/><br/>
    <input type="password" name="password" placeholder="Password" />
    <br/><br/>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

{% endblock %}

gamepredictor/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}

<h1>Create an Account:</h1>
<form method="POST" action="{% url 'accounts:user_signup' %}">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username" />
    <br /><br/>
    <input type="password" name="password1" placeholder="Password" />
    <br /><br/>
    <input type="password" name="password2" placeholder="Enter password again" />
    <br /><br/>
    <input class='btn btn-primary' type="submit" value="Signup!">
</form>

{% endblock %}

gamepredictor/games/templates/games/home.html
{% extends 'base.html' %}
{% block content %}
    <br/>
    <h4>Games for {{ today }}</h4>
    <br/>

    {% for game in games_data %}
    <p>
        <div class="cont" id="{{ game.game_id }}">
                <div class="logo away-team">
                    <img src='{{ game.away_team_logo }}'/>
                </div>
                <div class="detail-container">
                    <div class="game team-name away-team" id="{{ game.away_team }}{{ game.game_id }}">
                        {{ game.away_team }}
                    </div>
                    <div class="game stats">
                        {{ game.away_team_wins }}-{{ game.away_team_losses }}-{{ game.away_team_otl }}
                    </div>
                </div>

                <div class="separator">VS</div>
                <div class="detail-container">
                    <div class="game team-name home-team" id="{{ game.home_team }}{{ game.game_id }}">
                        {{ game.home_team }}
                    </div>
                    <div class="game stats">
                        {{ game.home_team_wins }}-{{ game.home_team_losses }}-{{ game.home_team_otl }}
                    </div>
                </div>

                <div class="logo home-team">
                    <img src='{{ game.home_team_logo }}'/>
                </div>
        </div>
    </p>

    {% endfor %}

    {% if user.is_authenticated %}
        <button id="submit">Submit Predictions!</button>
    {% else  %}
        <h4>Login or signup to make a prediction.</h4>
    {% endif %}

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    {% load static %}
    <script type="text/javascript" src="{% static 'games/scripts.js' %}"></script>

{% endblock %}

gamepredictor/stats/templates/stats/stats.html
{% extends 'base.html' %}
{% block content %}

    <h1>Stats for {{ user.username }}</h1>
    <p>Wins: {{ user_record.wins }} </p>
    <p>Losses: {{ user_record.losses }} </p>
    <p>OTL: {{ user_record.otl }} </p>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    {% load static %}
    <script type="text/javascript" src="{% static 'games/scripts.js' %}"></script>

{% endblock %}

gamepredictor/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>NHL Game Predictor</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'games/style.css' %}">
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">NHL Game Predictor</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Standings</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/stats/">Statistics</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Predictions</a>
              <a class="dropdown-item" href="#" onClick="document.getElementById('logout').submit()">Logout</a>
                <form method="POST" action="{% url 'accounts:user_logout' %}" id="logout">
                {% csrf_token %}
                <input type="hidden">
                </form>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:user_login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:user_signup' %}">Signup</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container text-center">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>